created blog
CV19Assist/app pull request #47
Opened 2020-04-05 22:20 UTC by MauricioSo

created the blog and the single pages of the blog

2020-04-06 00:01 UTC, thebitguru requested changes
I see that you did not end up using Redux.  Was that intentional?  Any chance you can incorporate it?  Please see the search page or other pages for samples.

2020-04-06 00:01 UTC, thebitguru commented on src/App.js
> +import SinglePost from './pages/SinglePost'
Can we please rename these to BlogPage and SinglePostPage?

2020-04-06 00:01 UTC, thebitguru commented on src/pages/Blog.js
> +    fetch("https://cv19assist.github.io/blog/index.json")
Can we move the URL to the [.env file](https://github.com/CV19Assist/app/blob/master/.env)?

2020-04-06 00:01 UTC, thebitguru commented on src/App.js
> +            <Route exact path="/needs/:slug" component={NeedDetails} />
Is this change expected?  I think you might have wanted to update the blog route on line 100.

2020-04-06 00:01 UTC, thebitguru commented on src/components/Post.js
> +      marginTop: "1em",
Please use the `theme` spacing instead of hard coding?  See [this](https://github.com/CV19Assist/app/blob/master/src/components/Homepage.js#L13) for reference.

2020-04-06 00:01 UTC, thebitguru commented on src/components/Post.js
> +    color: "rgb(85, 85, 85)"
Please use standard theme colors.  See the Material UI for standard styling.

2020-04-06 00:01 UTC, thebitguru commented on src/components/Post.js
> +    color: "primary",
Please use standard styling theme as documented on the Material UI site.

2020-04-06 00:01 UTC, thebitguru commented on src/pages/Blog.js
> +      .catch(err => console.log({ error: err }));
Can we account for 404 here, i.e. if a blog post isn't found, as well?

2020-04-06 02:47 UTC, MauricioSo commented on src/App.js
> +import SinglePost from './pages/SinglePost'
ok

2020-04-06 02:49 UTC, MauricioSo commented on src/App.js
> +            <Route exact path="/needs/:slug" component={NeedDetails} />
no, I changed the wrong line.

2020-04-06 02:49 UTC, MauricioSo commented on src/components/Post.js
> +      marginTop: "1em",
ok

2020-04-06 02:49 UTC, MauricioSo commented on src/components/Post.js
> +    color: "primary",
ok

2020-04-06 02:51 UTC, MauricioSo commented
I didn't know Redux was necessary for local state changes. I will implement it.

2020-04-06 02:55 UTC, MauricioSo commented
and thanks for the feedback¡

2020-04-09 04:34 UTC, thebitguru commented
@MauricioSo, as we had chatted on Slack, let's not worry about the redux pieces.  Can you please address the other comments?  Once you do, I will plan on merging the changes.  Thanks, again!

2020-04-10 01:42 UTC, merged