UI Tests For Request Workflows
CV19Assist/app pull request #99
Opened 2020-05-04 03:55 UTC by prescottprue

### Description

### Relevant Tickets (Please add `closes`, `refs`, etc)

- closes #90 

### Screenshots (if appropriate)

2020-05-05 06:53 UTC, thebitguru requested changes
This looks good, but we are missing the public comment tests.

Also, what's the thought on clearing our the database or specific records before/after the run?  This way it's easier to re-run the cypress tests without having to restart the emulator.

2020-05-05 06:53 UTC, thebitguru commented on src/routes/Request/components/RequestActions/RequestActions.js
> +    firestore.doc(`${USERS_COLLECTION}/${user.uid}`),
Unauthenticated users can see requests too, so, this is currently failing.

2020-05-05 19:46 UTC, prescottprue commented on src/routes/Request/components/RequestActions/RequestActions.js
> +    firestore.doc(`${USERS_COLLECTION}/${user.uid}`),
Oh shoot, ok - I was trying to add in the support for if you are system-admin, I can remove

2020-05-07 23:34 UTC, prescottprue commented on src/routes/Request/components/RequestActions/RequestActions.js
> +    firestore.doc(`${USERS_COLLECTION}/${user.uid}`),
Removed

2020-05-08 06:38 UTC, thebitguru approved these changes

2020-05-08 06:38 UTC, thebitguru commented on cypress/integration/RequestPage.spec.js
> +      // Set current user to super-admin role
Is this comment correct?  This implies that `role=null` is system admin, no?

2020-05-08 06:47 UTC, merged